---
abstract: 'AnyEvent::HTTP backend for ElasticSearch'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ElasticSearch-Transport-AEHTTP
requires:
  AnyEvent: 0
  AnyEvent::HTTP: 0
  ElasticSearch: 0.50
  ElasticSearch::Transport: 0
  ElasticSearch::Util: 0
  Encode: 0
  Scalar::Util: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/clintongormley/ElasticSearch-AEHTTP/issues
  homepage: https://metacpan.org/module/ElasticSearch
  repository: git://github.com/clintongormley/ElasticSearch-AEHTTP.git
version: 0.04
